name: Daily Network Health Check

on:
  schedule:
    # This runs at 17:00 UTC (12:00 PM Central Time) every day
    - cron: '0 17 * * *'
  workflow_dispatch: # This lets you trigger it manually from the GitHub website

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Run Monitor Script
        run: python monitor.py

      - name: Commit and Push Results
        run: |
          git config --global user.name "serolinen"
          git config --global user.email "mappnino@gmail.com"
          git add network_log.csv
          git commit -m "Automated Network Log Update: $(date)"
          git push